### ISSUE TITLE
Can't export files opened via Finder

### ISSUE THREAD

**Issue by root42** [Alexco500/sidplay5#1]
When I open a SID file via the finder, I can't export it to any file format. Only files from the collection can be exported. 

Great job on mainting SIDPlay! Thanks!

**Comment by Alexco500** [comment]
Yes, SIDPlay is very collection centric. Double-click in Finder does not work, but drag&drop does, at least here.
Can you please try, if that works for you as well?

**Comment by root42** [comment]
Cool, yeah. That's a workaround. Drag and drop and then export seems to be fine.

**Comment by Alexco500** [comment]
Please check new release v5.0.1-27 if that is fixing all your issues.
