### ISSUE TITLE
Enable close icon

### ISSUE THREAD

**Issue by Brog33** [Alexco500/sidplay5#10]
The close icon is disabled. Would be nice to be able to use it instead of having to press cmd+q

**Comment by Alexco500** [comment]
The normal behaviour would be that only the window is closed. So I guess this should be made configurable (close the window or close the entire application). I need to check that.

**Comment by Brog33** [comment]
Close the window (not quit the app) would probably be the most appropriate yes.

**Comment by Alexco500** [comment]
Just implemented it that way. Close will close the window and a new menu item lets you show that again.

**Comment by Brog33** [comment]
Are we talking about the close button/icon in the title bar? Because it's still grayed out here.

![image](https://user-images.githubusercontent.com/1303537/231829970-24ab9b22-7751-4cb2-be05-8660dc7d522a.png)
