### ISSUE TITLE
Sid library bug? Music sounds false/distorted on Mac /w AirPods

### ISSUE THREAD

**Issue by mournblade** [Alexco500/sidplay5#13]
I am *so* happy that someone has taken up this project. Unfortunately it doesn't solve my main issue with 4.2: 

If I start the app on my M1 Macbook Pro (latest running Ventura, but same before), and listen through my AirPods, AirPods Pro or AirPods Max, the sound is pretty bad. It sounds totally distorted and false. Hard to explain but you can hear what song it's supposed to be but it's not really listenable.

I have no idea what this is but hasn't anyone else heard this? It sounds fine through the MacBook speakers.

**Comment by Alexco500** [comment]
I can confirm that. Nice find, by the way. I (for whatever reason) never used my AirPods Max with SIDplayer, so I just tested that today.
Maybe that has something to do with the old audio interface the player uses, need to investigate that.

**Comment by mournblade** [comment]
Hey thanks for responding. I'm a huge sid guy since the demo days, used to listen regularly so it's really a bummer. 
FYI it's been this for years, ever since they released the M1. I filed a radar with Apple too back then but no response so far.

**Comment by Alexco500** [comment]
This one gave me a headache. Please test new beta-release. AirPods Max HomePod work here now and report back.

**Comment by mournblade** [comment]
Hi Alex, 

very sad to report that it doesn't work for me. tried Version 5.0.1 (29), running Ventura 13.3.1 (22E261) on my 2021 M1 MacBook Pro.

Tried both AirPods Max and Pro.

Happy to do any debugging you need, or an audio sample. I missed this reply not sure what is wrong with my GitHub responses. if you would like quick response reach me at mathias ampersand light labs (in one word) dot se

**Comment by Alexco500** [comment]
Please try the beta here
[https://github.com/Alexco500/sidplay5/releases/tag/v5.0.1_33_BETA](url)

**Comment by mournblade** [comment]
IT WOOOOOOOOORRRRRRRKKKKKSSSSSSSS!!!!!!!!!!!!! :):):)

Huge thanks, this has made my day. I can now spend the rest of the day coding away, listening to our old demo tunes!

**Comment by Alexco500** [comment]
Great that it works. Happy coding :-)
