### ISSUE TITLE
Repeat Song Bug

### ISSUE THREAD

**Issue by bluecursor** [Alexco500/sidplay5#16]
Just something I noticed tonight, repeat song is not working. Also In dark mode, its very hard to see these options being turned on as they are black on black.

**Comment by Alexco500** [comment]
Hm. Which repeat song button? The one to the right currently only repeats entire playlists, not single songs.
As for the dark mode, some improvement is already available in the beta version (https://github.com/Alexco500/sidplay5/releases/tag/v5.0.1_33_BETA), maybe you can test this version?
It should work with dark mode except for the search, I completely forgot about that :-(

**Comment by Alexco500** [comment]
Dark mode is fixed, repeat should work as well.
