### ISSUE TITLE
Feature Request: Play all Songs within one SID

### ISSUE THREAD

**Issue by sy2002** [Alexco500/sidplay5#20]
A lot of SIDs are containing multiple songs. One of many examples: Chris Huelsbeck's Katakis has 34 of them.

Current behavior: I start playing a multi SID song such as Katakis and it plays the first song. As soon as the first song is over, SIDPLAY goes to the next SID in the current HVSC folder, in my version this is "Madness".

Desired behavior: Having an option/a switch like "Play all Songs of a SID" that then does exactly this: First **all songs within a SID** are played one after another and **only then** , when the last song within the SID has been played, SIDPLAY goes to the **next SID**.

**Comment by mournblade** [comment]
This is interesting, and made me think. I don't think that any sid player I've ever used, on any platform, has had this feature. It's not for me, but I can totally see the use case! Cheers
