### ISSUE TITLE
Incoming FaceTime call totally destroys playback

### ISSUE THREAD

**Issue by mournblade** [Alexco500/sidplay5#25]
MacBook Pro, latest Ventura.

If I listen to Sidplay and receive an incoming call, what is playing becomes total white noise/distorted, killing the eardrums. It will remain that way until the app is restarted.

**Comment by Alexco500** [comment]
I just tested that with latest version. I listen to "Last Ninja", then receive an incoming call. The volume of Sidplay is lowered during the call, but raised again to normal level afterwards. It is not distorted or noise or whatever, during or after the call. So what is your exact setup? Are you using some Bluetooth devices or headphones?

**Comment by Alexco500** [comment]
Okay, reproduced. Should be fixed in the next release.
