### ISSUE TITLE
Bigger oscilloscope 

### ISSUE THREAD

**Issue by rettinghaus** [Alexco500/sidplay5#28]
It would be nice to make the oscilloscope bigger or toggle its view in the main window.

**Comment by Alexco500** [comment]
Hm. You mean bigger inside the info view? Or even enlarge the entire info view?
Or open a separate window with only the oscilloscope inside, e.g. like it is shown in the Quick Look Finder window?

**Comment by rettinghaus** [comment]
I think a separate window that could be maximized would be nice.
