### ISSUE TITLE
Feat: change subtune in playlists

### ISSUE THREAD

**Issue by Ph0B1uS** [Alexco500/sidplay5#5]
I cannot find a way to change what subtune is added to a playlist, neither before nor after the fact that it has been added and I believe that this would be a pretty cool feature.

Right now it seems like the default subtune set in the particular file is added and there's no choice to change at the time of adding or edit it later either.

**Comment by Alexco500** [comment]
Yes, you're right, the default subtune is added to the list.
But you should be able to change that, just click on the number in the "#" column, and you can enter a different number.
Not that easy to find, I guess.

**Comment by Ph0B1uS** [comment]
Would you look at that, it is actually editable in the playlist, cool!
I could see a scenario where one could drag the currently playing subtune from the display up top and dropping it into a playlist with it retaining the information about what actual subtune was playing at the time.

Not sure how hard that would be to accomplish but it's one way of doing it.

**Comment by Alexco500** [comment]
You mean dragging from the box with the animation/song info inside? That could be tricky, but I will see what I can do.
