### ISSUE TITLE
Feat: Add multiple subtunes to a playlist

### ISSUE THREAD

**Issue by Ph0B1uS** [Alexco500/sidplay5#6]
I would like the ability to add multiple subtunes to a playlist so that you could add subtune 1, 2 and 5 on separate entries in a list for instance.

**Comment by Alexco500** [comment]
If you change the subtune, like in #5 explained, you can at least add the same song with a different subtune via Drag & Drop (the default subtune is used).
Also, not obvious, I am open for ideas how to improve the subtune handling.
